from(bucket: "akasztenny's Bucket")
    |> range(start: -24h, stop: -23h)
    |> filter(fn: (r) => r["_measurement"] == "ticks")
    |> filter(fn: (r) => r["_field"] == "price")
    |> filter(fn: (r) => r["product"] == "BHMM/USD")
    |> aggregateWindow(every: 1h, fn: max, createEmpty: false)
    |> yield(name: "max")